version: '3.8'

services:
  uav_system_orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uav_ros2_jazzy_container
    network_mode: "host"
    ipc: "host"
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=42
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./drone_ws/src:/ros2_ws/src:rw
    command: /bin/bash -c "source /ros2_ws/install/setup.bash && ros2 launch uav_bringup full_mission_review.launch.py"
